<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>true</IsPackable>
	<Description>Common data structures, enums, and shared types for the Kitayec messaging library. This lightweight package contains pure data contracts used by both Abstractions and Infrastructure layers.</Description>
	<PackageTags>messaging;types;rossmann;erp</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kitayec.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
  </ItemGroup>

</Project>
