<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Erp.WmsConnector.Shared.Infrastructure.Tests.Unit" />
    <InternalsVisibleTo Include="Erp.WmsConnector.Shared.Testing" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kitayec" Version="1.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.9.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.3" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Erp.WmsConnector.Shared.Abstractions\Erp.WmsConnector.Shared.Abstractions.csproj" />
  </ItemGroup>

</Project>